### PR TITLE
update hello sample

### PR DESCRIPTION
**Pull request by BogdanZavu**
The existing sample code does not compile on windows. I have not tested on other platforms.

### CODE REVIEW

**Comment by hroederld** [comment]
Hi thanks for your PR. I have a guess about what is going on here.

We have CI on this repo that builds on Linux / OSX / Windows, and the the Windows CI is working. The SDK does have this weird functionality where if you compile it with as C++ it actually exposes an `LDClient` class instead of `struct LDClient`, Which you can see here https://github.com/launchdarkly/c-client-sdk/blob/master/ldapi.h#L600

Is it possible this is what you are running into? This is confusing though and we will probably do it differently in the future 2.0 release.

**Comment by BogdanZavu** [comment]
Don't think so, looking at what's exported i see this :
LD_EXPORT(struct LDClient_i *) LDClientInit(LDConfig *const config,
    LDUser *const user, const unsigned int maxwaitmilli);

LD_EXPORT(bool) LDBoolVariation(struct LDClient_i *const client,
    const char *const featureKey, const bool fallback);

**Comment by hroederld** [comment]
When you say "looking at what's exported" do you mean you printed the symbol table from the binary or read the source?

There is a section near the bottom that aliases `struct LDClient_i` to `LDClient` if compiled with plain C: https://github.com/launchdarkly/c-client-sdk/blob/master/ldapi.h#L592

**Comment by BogdanZavu** [comment]
I just read the source and I only looked at the grouped type defs from top. 
So what should we do for C++ ? 
#if !defined(__cplusplus) && !defined(LD_C_API)
/** @brief Opaque client object **/
typedef struct LDClient_i LDClient;
#endif

**Comment by BogdanZavu** [comment]
And I assume we have to get rid of LDClient* at the end through client->close(); ?

**Comment by hroederld** [comment]
Yes that will free up the resources. Hope that all helps!

**Comment by BogdanZavu** [comment]
There is an issue, the feature evaluation does not work when using the code above.
I can see this in the console :
LD: sending events failed deleting event batch

**Comment by hroederld** [comment]
Can you please post a more complete set of logs?

**Comment by BogdanZavu** [comment]
Sure, this is all I see in the console :
LD: Setting user key to: 4404fff1-0b3f-48f2-856e-adb8cbdd068c
LD: connecting to stream https://clientstream.launchdarkly.com/meval/eyJrZXkiOiI0NDA0ZmZmMS0wYjNmLTQ4ZjItODU2ZS1hZGI4Y2JkZDA2OGMiLCJhbm9ueW1vdXMiOnRydWV9
LD: sending events failed deleting event batch

**Comment by hroederld** [comment]
Sorry it is not clear to me what is happening. Can you post the relevant SDK usage code (with keys or private info redacted).

**Comment by BogdanZavu** [comment]
LDConfig* config = LDConfigNew(YOUR_MOBILE_SDK_KEY);
    LDUser* user = LDUserNew(nullptr);
    LDClient* client = LDClient::Init(config, user, 3000);
    int show_feature = client->boolVariation(YOUR_FEATURE_KEY, false);
    client->close();

**Comment by hroederld** [comment]
Thanks. I will spin up a VM and try to validate functionality.

**Comment by hroederld** [comment]
Hi @BogdanZavu 

I went and built / ran the hello app in a Windows 10 VM and everything worked for me.

Did you actually set `YOUR_MOBILE_SDK_KEY` to your mobile sdk key?

**Comment by BogdanZavu** [comment]
Yes, and it works when using the variant with LCDClient_i
Have you compiled with c++ ? if so, can you post the whole hello world sample here ?

**Comment by hroederld** [comment]
Oh that is an interesting piece of information. Let me try that out.

**Comment by hroederld** [comment]
Nope it also works with the c++ interface for me. The `hello.cpp` I used is is:

```
#include <stdbool.h>
#include <stdio.h>
 
#include "ldapi.h"
#include "uthash.h"
 
void logger(const char *s) {
    printf("LD: %s\n", s);
}
 
int main() {
    LDSetLogFunction(LD_LOG_INFO, logger);
 
    LDConfig *config = LDConfigNew("redacted");
    char* key = "bob@example.com";
    LDUser *user = LDUserNew(key);
 
    // wait up to 3 seconds to connect
    LDClient *client = LDClient::Init(config, user, 3000);
 
    int show_feature = client->boolVariation("test", false);
    if (show_feature) {
        // application code to show the feature
        printf("Showing your feature to %s\n", key);
    } else {
        // the code to run if the feature is off
        printf("Not showing your feature to %s\n", key);
    }
 
    client->close();
 
    return 0;
}
```

and I compiled with: `cl /Fe: hello.exe hello.cpp /link ldclientapi.lib` in a VS command prompt.

**Comment by BogdanZavu** [comment]
I confirm it is working when compiled with C++ in Visual Studio 2019.
Also I update the sample based on your latest feedback.
Maybe it is worth mentioning somewhere that ldclientapi.dll is built with release configuration ?

**Comment by hroederld** [comment]
While I'm glad that the SDK is now working for you. I can't really merge this PR as it would break the existing C example, trading one for the other. The preprocessor based class vs struct definition switch is confusing through and is being removed which will eliminate the confusion. The 2.0.0 implementation changes are under active development already.

It is definitely worth mentioning the release configuration build part, as that is more important to know on Windows than other platforms. We will start doing so.

**Comment by BogdanZavu** [comment]
One more thing @hroederld , if you are making a new build/version can you add version info and copyright and all the other fields in the properties of ld.dll ? It's a legal issue, we need to have an inventory of third-parties components. Thank you

**Pull request closed without merging**
